---
title: "logistic regression"
author: "Jiaying Wu"
date: "18/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

sample <- diamonds %>%
  mutate(color_E = if_else(color == "E", 0 , 1))

ggplot(sample, aes(x = x, y = color_E))+
  geom_jitter(height = 0.05, alpha = 0.1) +
  geom_smooth(se = FALSE)
```


### Logistic regression for modeling color_E variable with diamond variable

```{r}
# remobve color variable since we use this variable to create color_E
sample <- sample %>%
  select(-color)

# use "binomial" family for count data with 2 class {0,1}
glm_mod <- glm(formula = color_E~., data = sample, family = "binomial")

# Remeber the value here is not the proability, you can intepret it as increasing the predicted value, then the predicted provability is the predicted value apllying some transformation.
summary(glm_mod)
```

### Residuals Plot

```{r}
library(broom)
glm_aug <-augment(glm_mod)
ggplot(glm_aug, aes(x = .fitted, y = .resid)) +
  geom_point(alpha = 0.1)
```



```{r}
# specific response to get the probability
sample <- sample %>%
  mutate(prediction = predict(glm_mod, sample, type = "response"))

ggplot(sample, aes(x = x, y = prediction))+
  geom_point(alpha = 0.1)
```




